### ISSUE TITLE
Package OxyPlot.Xamarin.Forms 1.0.0 is not compatible with xamarinmac20 

### ISSUE THREAD

**Issue by olivercortinas** [oxyplot/oxyplot-xamarin#100]
I was trying to install OXYPLOT.XAMARIN.FORMS by nuget to a Xamarin.Forms project and get this exception:

Package OxyPlot.Xamarin.Forms 1.0.0 is not compatible with xamarinmac20 (Xamarin.Mac,Version=v2.0) / win-x64. Package OxyPlot.Xamarin.Forms 1.0.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - portable-monoandroid10+net45+win+win81+wp8+wpa81+xamarinios10 (.NETPortable,Version=v0.0,Profile=win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10)
  - uap10.0 (UAP,Version=v10.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)

Any idea?

**Comment by objorke** [comment]
I think we release a pre-release package that works with more recent versions of Xamarin.
I recommend including the OxyPlot Xamarin as a git submodule/subtree and building these projects yourself from the latest source code.

**Comment by objorke** [comment]
See #84

**Comment by janusw** [comment]
We just published a new package that includes Mac support (https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/2.0.0-beta.1), which should fix this issue.
