### ISSUE TITLE
Outdated nuget package

### ISSUE THREAD

**Issue by prabakaranr** [oxyplot/oxyplot-xamarin#102]
Hi,

Thank you for such an excellent work. This really saves a lot of valuable time for Xamarin developers.

The latest [nuget package](https://www.nuget.org/packages/OxyPlot.Xamarin.Forms) was released on 1/8/2017, but does not include recent changes added in source. Could we expect a new release of nuget package with the latest source changes, or do we have to compile the source and use the assemblies manually every time?

Thanks,
Prabakaran

**Comment by objorke** [comment]
See #84

**Comment by janusw** [comment]
A new package was just published: https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/2.0.0-beta.1
