### ISSUE TITLE
OxyPlot.Xamarin.Forms NuGet Package Issue

### ISSUE THREAD

**Issue by Auto72** [oxyplot/oxyplot-xamarin#103]
When you install the OxyPlot.Xamarin.Forms in your project, you get the following Warning NU1701:

Package 'OxyPlot.Xamarin.Forms 1.1.0-unstable0011' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

So it doesn't work in your project. Can you fix it please?

**Comment by objorke** [comment]
See #84

**Comment by Auto72** [comment]
I tried to include the source code in my project. Thanks.
