### ISSUE TITLE
Left and Right most datapoints are clipping in lineseries

### ISSUE THREAD

**Issue by SwathiAdari27** [oxyplot/oxyplot-xamarin#106]
I have tried with **minimumPadding** property on graph, but it only works when we don't add **minimum** and **maximum** property. 

Can we add padding along with minimum and Maximum values to the graph??

Could anyone let us know if it is possible. any suggestions are very much helpful.

**Comment by VisualMelon** [comment]
This is not presently possible. I've been thinking about this for a looong time, and finally wrote something about it in https://github.com/oxyplot/oxyplot/issues/1569.

**Comment by objorke** [comment]
This should be implemented in oxyplot core: oxyplot/oxyplot#1569
