### ISSUE TITLE
How to add points in a LineSeries dynamically

### ISSUE THREAD

**Issue by xroot3** [oxyplot/oxyplot-xamarin#107]
I try to add points in a LineSeries dynamically In a System.Timer，but it can not refresh real time ，what can I do to solve it?

**Comment by VisualMelon** [comment]
The library doesn't do any automatic refreshing (e.g. when you add/change datapoints): you need to call `PlotModel.Invalidate(true)` when you change data. This forces the series to update, and should cause the UI to refresh at its next convenience.

**Comment by xroot3** [comment]
Thank you very much,I can draw it dynamically success!!!
