### ISSUE TITLE
Package OxyPlot.Xamarin.Android 1.0.0 compatible with netstandard2.0 (.NETStandard,Version=v2.0)

### ISSUE THREAD

**Issue by parameshgolla** [oxyplot/oxyplot-xamarin#108]
Hi,
My Xamarin APP is based on .NET2.0 and trying to use Oxyplot for charting. But, it complains compatiblity issue. please provide support for .net 2.0. 
Issue: Package OxyPlot.Xamarin.Android 1.0.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0)

**Comment by objorke** [comment]
See #84. The NuGet package is outdated, I suggest to include the component as a git submodule and build it with your app!

**Comment by parameshgolla** [comment]
how do I include  OxyPlot.Xamarin.Android as a git submodule to my Xamarin Android APP. Any leads please..

**Comment by objorke** [comment]
This assumes that you are using git in your project:
```
git submodule add https://github.com/oxyplot/oxyplot-xamarin.git
```
Then include the C# projects you need in your solution.

**Comment by parameshgolla** [comment]
Thank u for the quick response. Will try it out. But, It would be good to have updated OxyPlot.Xamarin.Forms.Android Nuget package supporting .net 2.0

**Comment by janusw** [comment]
We just published a new OxyPlot.Xamarin.Forms package that supports netstandard2.0: https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/2.0.0-beta.1

Is that sufficient for you, or do you actually need a OxyPlot.Xamarin.Android package? (There are currently no plans to continue supporting this.)

**Comment by janusw** [comment]
> Is that sufficient for you, or do you actually need a OxyPlot.Xamarin.Android package? (There are currently no plans to continue supporting this.)

Actually all the stuff from the old OxyPlot.Xamarin.Android package is included in the OxyPlot.Xamarin.Forms now, so you should simply be able to reference it from your .NET Standard 2.0 Xamarin.Android project.

Therefore I'll close this issue. In case you still have problems, please open a new issue.
