### ISSUE TITLE
Error During Compile

### ISSUE THREAD

**Issue by alberk8** [oxyplot/oxyplot-xamarin#11]
Hi,

I have OxyPlot.Xamarin.Andriod (v1.0.0-unstable1983) installed with OxyPlot.Core (v2015.1.708-alpha)

When I compile the sample code I get the following Error.  Please help.

Unable to resolve interface type 'OxyPlot.IPlotView'. Are you missing an assembly reference?

The element 'LinearLayout' has invalid child element 'OxyPlot.Xamarin.Android.PlotView'.

I am using Visual Studio 2015 Update 3 with Xamarin 4.1.1.3.

**Comment by ahmedalejo** [comment]
don´t know if you resolved your issue. If so? share your solution and close.

If not? please share you android layout file.

Obs: [OxyPlot.Xamarin.Andriod (v1.0.0-unstable1983)](https://www.nuget.org/packages/OxyPlot.Xamarin.Android/1.0.0-unstable1983) depends specifically on [OxyPlot.Core (= 1.0.0-unstable1983)](https://www.nuget.org/packages/OxyPlot.Core/1.0.0-unstable1983)

**Comment by objorke** [comment]
can we close this? the CI build is currently passing!

**Comment by Meurth** [comment]
the element linearlayout has invalid child element oxyplot.xamarinandroid.plotview

wtf is going on? Why does NOBODY seem to have the same issue?

**Comment by alberk8** [comment]
Hi,

I have long abandon using this.  Nobody seems to care.  Try this, its free also and at least there is support a bit slow but they do answer every questions.   It is free even for commercial use as long as you fall within the revenue range and developer size.  It's a fair deal.
www.syncfusion.com

**Comment by Meurth** [comment]
thanks alberk8, I'll look into that
