### ISSUE TITLE
Upgrade to Xamarin.Forms 2.3

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot-xamarin#13]
https://github.com/oxyplot/oxyplot-xamarin/blob/develop/Source/OxyPlot.Xamarin.Forms/packages.config
https://www.nuget.org/packages/Xamarin.Forms/

**Comment by prajithmp** [comment]
do we have a new update soon ?

**Comment by smitaA** [comment]
Do we have any updates to support for Xamarin.Forms 2.3 on Android?

**Comment by MKahmen** [comment]
@prajithmp @smitaA 
I figured out that it works when you just compile the right projects from this repo or reference the project.

Here's what to do (only in Xamarin.Forms.Android-Project, no need to touch the PCL or iOS):
- Use nuget to download Oxyplot.Xamarin.Android
- Reference these two DLLs or reference the projects from this repo:
  _OxyPlot.Xamarin.Forms.dll
  OxyPlot.Xamarin.Forms.Platform.Android.dll_

Or just download them and add them: [dlls.zip](https://github.com/oxyplot/oxyplot-xamarin/files/423191/dlls.zip)

This will bring it back to work until Nuget or Myget files are updated.

**Comment by prajithmp** [comment]
@MKahmen ,  i am able to compile the project without any errors now, but not able to deploy it to any android device or simulator.

its showing error deploy failed "There were deployment Errors. Do you want to Continue?"

why is this happening..

**Comment by MKahmen** [comment]
@prajithmp you need to be more specific. check the log. If you're using Xamarin Studio just click on the error message to open it.

**Comment by prajithmp** [comment]
@MKahmen  i am using visual studio, there is no error listed.  Only this message box appearing on deployment. that is why i got confused. let me check again...

**Comment by MKahmen** [comment]
@prajithmp
Check the build and/or device log.

**Comment by prajithmp** [comment]
@MKahmen i had some issue with the packages in existing project. when i tried in a new solution, its working fine.
thanks.

**Comment by objorke** [comment]
OxyPlot.Xamarin.Forms.1.0.0-unstable0652 on myget should now support 2.3.1.114

**Comment by MKahmen** [comment]
Thanks @objorke 
works great!

**Comment by prajithmp** [comment]
how can i install OxyPlot.Xamarin.Forms.1.0.0-unstable0652 to my Visual Studio (xamarin.forms) project , i cannot find in 'Manage Nuget Package' window.

**Comment by MKahmen** [comment]
@prajithmp
It's not on Nuget. It's on myget. Get the repo from OxyPlots website and download the prerelease version via VS Package Manager.

**Comment by prajithmp** [comment]
@MKahmen
i could not find any myget repo for (OxyPlot.Xamarin.Forms) from oxyplots website. only i could find is oxyplot core repo https://www.myget.org/feed/oxyplot/package/nuget/OxyPlot.Core. please guide me.

**Comment by MKahmen** [comment]
@prajithmp http://www.oxyplot.org/announcements/nuget-packages

**Comment by objorke** [comment]
The projects have been updated XF 2.3.2.127, this will be included in v1.0

**Comment by Nandulucky** [comment]
When Im adding OxyPlot.Xamarin.iOS nuget package but I got an error like below

> Could not install package 'OxyPlot.Xamarin.iOS 1.0.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package .

How can I resolve this issue.
VisualStudio version: 7.4.2(build 12)


Thanks
