### ISSUE TITLE
Inconsistent versioning of nuget packages

### ISSUE THREAD

**Issue by ahmedalejo** [oxyplot/oxyplot-xamarin#14]
There´s a grave issue with the versioning after the package where moved to [MyGet] to show this

the latest version on [Nuget.org](Nuget.org)
[OxyPlot.Xamarin.Forms.1.0.0-unstable1983](https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/1.0.0-unstable1983) was updated `Sunday, February 7, 2016`

while on [MyGet.org](MyGet.org) we have
 [OxyPlot.Xamarin.Forms.1.0.0-unstable0645]() updated on`Sat, 27 Aug 2016 05:50:25 GMT`

**OxyPlot.Xamarin.Forms.1.0.0-unstable1983** should be older than 
**OxyPlot.Xamarin.Forms.1.0.0-unstable0645**

**Comment by objorke** [comment]
Will unlist all prerelease packages on nuget.org!

**Comment by janusw** [comment]
It seems that most unstable packages have been unlisted from nuget.org. Also we have published a 2.0.0 package by now. So I guess this can be closed.
