### ISSUE TITLE
Can't select an isolated datapoint.

### ISSUE THREAD

**Issue by giacarrea** [oxyplot/oxyplot-xamarin#145]
Using avalonia oxyplot 2.10 on windows 11 pro, I can't click on datapoints that are nested between two DataPoint.Undefined. (In my example, the broken lines are displayed as dashed)

Tough it is possible to select isolated points by selecting regular points, then dragging the mouse cursor to them.

![image](https://user-images.githubusercontent.com/60611503/220398267-bf91156e-ed95-463b-b011-1d35ae8a3ea5.png)

**Comment by janusw** [comment]
Wrong project? You probably want to report this here: https://github.com/oxyplot/oxyplot-avalonia
