### ISSUE TITLE
.Net Maui Support

### ISSUE THREAD

**Issue by jaison-t-john** [oxyplot/oxyplot-xamarin#148]
Hi, When can we expect an official plugin support for .Net Maui. Here is an implementation of the same https://github.com/iniceice88/OxyPlot.Maui.Skia

**Comment by janusw** [comment]
> Hi, When can we expect an official plugin support for .Net Maui.

Good question. Initially, I was hoping to port this repo from Xamarin to MAUI, but I haven't found the time yet. I'm currently not sure if and when this will happen.

> Here is an implementation of the same https://github.com/iniceice88/OxyPlot.Maui.Skia

Indeed this looks like a good starting point for a MAUI implementation of oxyplot, which would be an alternative to porting oxyplot-xamarin to MAUI. See the discussion in https://github.com/oxyplot/oxyplot/issues/1958.

**Comment by janusw** [comment]
> > Here is an implementation of the same https://github.com/iniceice88/OxyPlot.Maui.Skia
> 
> Indeed this looks like a good starting point for a MAUI implementation of oxyplot

Actually this repository has been moved to https://github.com/oxyplot/oxyplot-maui by now and is becoming the "official" MAUI port of oxyplot. Therefore I don't think there is any need for porting oxyplot-xamarin to MAUI. I'm closing this ticket.
