### ISSUE TITLE
OxyPlot.Xamarin.Forms nuget package does not include UWP platform.

### ISSUE THREAD

**Issue by tkgdsg** [oxyplot/oxyplot-xamarin#16]
OxyPlot already supports UWP platform, but nuspec file,
oxyplot-xamarin/Source/OxyPlot.Xamarin.Forms/OxyPlot.Xamarin.Forms.nuspec.
does not contain a description about UWP platform.

**Comment by objorke** [comment]
I tried to add it to the nuspec, but not sure if I got the monikers and target folders correct
Try the latest package from myget: OxyPlot.Xamarin.Forms.1.0.0-unstable0652

**Comment by objorke** [comment]
I tested it and the uap project does not work. Do we need a project.json file?

**Comment by sillerjp** [comment]
Hi, 

I cannot find OxyPlot.Xamarin.Forms.Platform.UWP.PlotViewRenderer.Init(); in any library, when I install Oxyplot.XamarinForms to my projects, everything is installed correctly for iOS and Android but UWP project only installs this assembly. Where can I get the proper UWP assemblies?

Thanks,
Regards

**Comment by objorke** [comment]
This should be solved in OxyPlot.Xamarin.Forms.1.1.0-unstable0011
