### ISSUE TITLE
SimpleDemo UWP release not showing?

### ISSUE THREAD

**Issue by dimitrijevic** [oxyplot/oxyplot-xamarin#2]
Is it just me or is the OxyPlot in Release configuration of the SimpleDemo app on Universal Windows Platform not showing up?
It shows up fine in Debug?
TIA

EDIT: Looking at output, two System.IO.FileNotFoundExceptions are thrown trying to access some System.Private.Reflection.Core stuff, but probably caught as they don't cause the app to crash...my guess...something gets funky during .net optimizer work and might probably be patched using some directives in the rd.xml file of the universal dll, but I can't figure out why the OxyPlot project's been split since that surely can't help locating what should be fixed...strangely, non-Xamarin SimpleDemo10 works?

**Comment by clarkis117** [comment]
@dimitrijevic  I'm trying on Xamarin forms and can't get it to show in debug until the window resizes

**Comment by objorke** [comment]
maybe the PlotViewRenderer.Init() code is optimized away?

**Comment by dimitrijevic** [comment]
Thanks to @mattwhilden and @objorke, this issue has been found to have a workaround https://github.com/oxyplot/oxyplot-xamarin/pull/53 and you can publish UWP apps to the store with OxyPlot.Xamarin as http://smarturl.it/ScolioMetro

**Comment by MattWhilden** [comment]
Fantastic news. Do let us know if you have any other issues/comments with .NET Native/UWP stuff (dotnetnative@microsoft.com). Very happy to be able to help out.

**Comment by sreekarsudireddy** [comment]
OxyPlot graphs in Windows Forms UWP not visible until windows resize(Orientation changed).

**Comment by lionelmennig** [comment]
@sreekarsudireddy I can confirm this one. Did you find any way/trick to fix it ?

**Comment by sreekarsudireddy** [comment]
@leeyo We were able to get the OxyPlot chart to be displayed in UWP without any issue if the chart is the only child of the containing parent page (for ex. ContentPage).

But if the ContentPage has children other then the graph, the graph fails to show up on the first load (unless the screen orientation changes).

**Comment by lionelmennig** [comment]
@sreekarsudireddy This point about the parent is good to know, but couldn't help in my case. :( Did you try some logical size/orientation change from code to see if it fixes it on launch ?

**Comment by sreekarsudireddy** [comment]
@leeyo We tried something similar but failed to achieve the desired result on page load. But we had a situation where we got a picker(dropdown) just above the chart. The chart shows up when we expanded the picker.

By this, we understood that any change event will trigger the update event of the chart. So finally, we moved to Telerik Controls.

**Comment by lionelmennig** [comment]
@sreekarsudireddy After some research, I figured out that this bug was fixed on v1.1.0-unstable0011. :) Btw I'm having troubles on iOS aswell when charts are disposed in a listview (only rendering "screen visible rows" charts and reusing these charts (!) for below rows).

**Comment by cesarau41** [comment]
Thanks to @MattWhilden  and @objorke !! You guys are life savers!! The workaround worked like a charm.
