### ISSUE TITLE
How to install from nuget (UWP)

### ISSUE THREAD

**Issue by gaminn** [oxyplot/oxyplot-xamarin#33]
Are there instructions how to install OxyPlot for Xamarin.Forms for UWP platform?

This is what I tried, without success:
I installed OxyPlot.Xamarin.Forms v1.0.0-unstable1983 to both portable and UWP project of my Xamarin.Forms solution. Then I tried to install OxyPlot.Windows v1.0.0 to UWP project of my Xamarin.Forms solution, but got this error: 

```
Version conflict detected for OxyPlot.Core. 
 BlankAppXamlXamarinForms.UWP (>= 1.0.0) -> OxyPlot.Windows (>= 1.0.0) -> OxyPlot.Core (= 1.0.0) 
 BlankAppXamlXamarinForms.UWP (>= 1.0.0) -> OxyPlot.Xamarin.Forms (>= 1.0.0-unstable1983) -> OxyPlot.Core (= 1.0.0-unstable1983).
```

**Comment by NPadrutt** [comment]
I uses for the uwp version of the App the package Oxyplot.Windows who has the version v2015.1.1033-alpha. This works so far for me.

**Comment by objorke** [comment]
I pushed `OxyPlot.Xamarin.Forms.1.1.0-unstable0011` to nuget.org
I will update the docs - it seems to work on my machine now!
http://docs.oxyplot.org/en/latest/getting-started/hello-xamarin-forms.html

**Comment by objorke** [comment]
@gaminn Can we close this issue?

**Comment by janusw** [comment]
I have published a OxyPlot.Xamarin.Forms 2.0.0 package yesterday, which includes OxyPlot.Windows and references OxyPlot.Core version 2.0.0. This issue certainly can be closed.
