### ISSUE TITLE
HeatMapRenderMethod enum missing

### ISSUE THREAD

**Issue by OllieStrevel** [oxyplot/oxyplot-xamarin#44]
Hello everybody!

I'm recently using OxyPlot in Xamarin iOS & Xamarin.Android, and I've downloaded the package via Nuget: 
Package: **OxyPlot for Mobile Devices (Windows Store/Windows Phone/Android/iOS**
Identifier: **Oxyplot.Mobile** 
Version: **2015.1.744-alpha**

I'm trying to run this example:
http://docs.oxyplot.org/en/latest/models/series/HeatMapSeries.html#example-linear-bitmap

BUT im getting errror in this line:
`RenderMethod = HeatMapRenderMethod.Rectangles,`

I checked the Namespace, i notice that the `HeatMapRenderMethod` enum is missing and the `HeatMapSeries` class not have a `RenderMethod` at least in mobile version.

Anyone? Thanks

**Comment by objorke** [comment]
OxyPlot.Mobile is outdated. The pre-release Xamarin packages are currently only available on myget.
They should all target OxyPlot.Core v1.0
There could be a dependency issue with the Xamarin packages, but there should not be an issue with the enum, I think.

**Comment by objorke** [comment]
Will close this since OxyPlot.Mobile is outdated
