### ISSUE TITLE
fix bitrise.io build

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot-xamarin#54]

**Comment by dimitrijevic** [comment]
Tried to setup secondary workflow, removing the certificate signing, and got the, missing 'OxyPlot.Core', concretely:

> Unable to find version '1.0.0' of package 'OxyPlot.Core'

 (it exists, thus, maybe it's them, I'll upgrade nuget step, but I have to rebuild...how much build mins you've got? 200x10min/bld might not go a long way with me learning to set bitrise.io up by trial and error @objorke :)

**Comment by dimitrijevic** [comment]
Here's some further known issues, which as I suspected, may just indicate, bitrise.io's fault: https://github.com/bitrise-steplib/steps-nuget-restore/issues/15
I'll could try that cache workaround...but...if I can rebuild then, is certification step really important to you?
I was looking at the apple developer account I've got access to, and I've got no certificates for mac development there (if those even exist, there's just ios, tvos, watchos certificates unfortunately)...

**Comment by dimitrijevic** [comment]
It didn't work with the upgraded nuget restore step (from 0.9.3 to 1.0.3), so either they've got issues restoring OxyPlot.Core and/or it's something in the nuget itself (but I can find it) ... I'll take a look at the cache:pull/push steps although adding caches to an automated build instead of trying to get the currently referenced nuget might just defeat the purpose of CI...

**Comment by dimitrijevic** [comment]
Is this still an issue, sorry I was not around much, I'll take another look at it soon...

**Comment by objorke** [comment]
I have not checked this since I created the issue.

**Comment by dimitrijevic** [comment]
Tried it today, still failing, obviously :) though error is different, also is issue #65 related?
I was wondering about .NET standard support and would it be viable soon given SkiaSharp isn't used...
Or am I mistaken about that maybe?

**Comment by janusw** [comment]
Bitrise is not being used any more. We have a GitHub Actions build job now. Closing.
