### ISSUE TITLE
Is Windows 8.1 supported?

### ISSUE THREAD

**Issue by charlesroddie** [oxyplot/oxyplot-xamarin#58]
Is there an intention to support Windows 8.1 from Xamarin Forms? Unfortunately we are stuck on Windows 8.1 for the time being.
The software on here currently has a Windows 8.1 project but doesn't have any OxyPlot references and so fails when run.
Just asking for information. Thanks.

**Comment by objorke** [comment]
The current intention is to support iOS, Android and UWP on Xamarin Forms.

There is Windows 8 code at
https://github.com/oxyplot/oxyplot/tree/develop/Source/OxyPlot.Windows8
