### ISSUE TITLE
Is there any way to use Tracker in Xamarin.iOS platform?

### ISSUE THREAD

**Issue by prakashshaiva** [oxyplot/oxyplot-xamarin#59]
Is there any way to use Tracker in Xamarin.iOS platform?

**Comment by ArgusMagnus** [comment]
Also, is there a way to use it in a Xamarin.Android Project?

**Comment by objorke** [comment]
I don't think this has been implemented for iOS and Android yet, see #26

**Comment by objorke** [comment]
Duplicate for #26
