### ISSUE TITLE
Is the Xamarin.Mac port still supported?

### ISSUE THREAD

**Issue by joa77** [oxyplot/oxyplot-xamarin#65]
I'm wondering wether the Xamarin.Mac port is still supported, because the NuGet Package is not updated since 2015 an marked as deprecated.

**Comment by objorke** [comment]
The OxyPlot Xamarin releases are a bit behind. I have not been able to test these platforms myself lately. Need more contributors/testers on all these platforms...

**Comment by dsyme** [comment]
@objorke I've started using this library as an extension for https://fsprojects.github.io/Elmish.XamarinForms/ and have Mac, Android, iOS and Windows devices in my office, I may be able to help test here.  

Ping me if needed

**Comment by objorke** [comment]
See NuGet package `v2.0.0-previes0001`. Hopefully we can publish a stable version soon.
