### ISSUE TITLE
OxyPlot.Xamarin.Forms support for MacOS

### ISSUE THREAD

**Issue by HenryHatten** [oxyplot/oxyplot-xamarin#71]
Xamarin.Forms now runs also on Macs, but there does not seem to be any support for this in OxyPlot.Xamarin.Forms, and no way to initialise the renderer. Is there any chance that this will be get updated/implemented?

**Comment by objorke** [comment]
This should now be supported

**Comment by dsyme** [comment]
Fantastic!

**Comment by ekrogh** [comment]
I have installed OxyPlot.Xamarin.Mac (2.0.Q-preview0001) in the .macOS project, but when I try to install OxyPlot.Xamarin.Forms to the ,macOS project I get the error messages
"
Retrieving package 'OxyPlot.Xamarin.Forms 1.1.0-unstable0011' from 'nuget.org'.
For adding package 'OxyPlot.Xamarin.Forms.1.1.0-unstable0011' to project 'oxyPlotTst.macOS' that targets 'xamarinmac20'.
Install failed. Rolling back...
Package 'OxyPlot.Xamarin.Forms.1.1.0-unstable0011 : OxyPlot.Core [2.0.0-unstable0956, ), Xamarin.Forms [2.3.3.180, )' does not exist in project 'oxyPlotTst.macOS'
Package 'OxyPlot.Xamarin.Forms.1.1.0-unstable0011 : OxyPlot.Core [2.0.0-unstable0956, ), Xamarin.Forms [2.3.3.180, )' does not exist in folder '/Users/eks/projects/xamarinProjs/OxyPlotTst/packages'
Executing nuget actions took 61 ms
Could not install package 'OxyPlot.Xamarin.Forms 1.1.0-unstable0011'. You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
"

How do I solve that problem ?

-- Eigil
