### ISSUE TITLE
Update to Xamarin.Forms 4.0

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot-xamarin#78]
https://www.nuget.org/packages/Xamarin.Forms

See #73

**Comment by dsyme** [comment]
@objorke It would be fantastic to see this project reach reach 2.0.0 status.  Is there any chance you could post an issue detailing where we're at with that and how people like myself might be able to help?

Thanks!
don

**Comment by objorke** [comment]
Hi Don! I agree it would be great to achieve the 2.0 release! I will update the milestone https://github.com/oxyplot/oxyplot-xamarin/milestone/2 to include the issues I think should be addressed.

**Comment by objorke** [comment]
The project has been updated to 4.3.0
https://github.com/oxyplot/oxyplot-xamarin/blob/develop/Source/OxyPlot.Xamarin.Forms/OxyPlot.Xamarin.Forms.csproj#L20
