### ISSUE TITLE
(Mac) PlotModel mouse event args' Position is relative to the window, instead of the PlotView

### ISSUE THREAD

**Issue by chaselal** [oxyplot/oxyplot-xamarin#81]
I don't have a repro project.

On WPF, PlotModel mouse events like PlotModel.MouseEnter, PlotModel.MouseLeave, and PlotModel.MouseDelta are given OxyMouseEventArgs with Position relative to the PlotView. The same is true on iOS and Android.

On Mac, the same events' args are given Positions relative to the window.

The difference in behavior makes it harder to observe mouse events in a platform-agnostic way.

**Comment by chaselal** [comment]
I believe a fix would involve following the instructions in the [`locationInWindow` documentation](https://developer.apple.com/documentation/appkit/nsevent/1529068-locationinwindow?language=objc):

> In a method of a custom view that handles mouse events, you commonly use the locationInWindow property in conjunction with the NSView method convertPoint:fromView:to get the mouse location in the view’s coordinate system. For example:
> 
> ```
> NSPoint event_location = theEvent.locationInWindow;
> NSPoint local_point = [self convertPoint:event_location fromView:nil];
> ```

Oxyplot would need to do something like

```
PlotView plotview;
plotVIew.ConvertPointFromView(event.LocationInWindow, null);
```

This should be done whenever OxyPlot translates from an AppKit mouse event to an OxyPlot ScreenPoint.

E.g. https://github.com/oxyplot/oxyplot-xamarin/blob/develop/Source/OxyPlot.Xamarin.Mac/ConverterExtensions.cs#L201

**Comment by chaselal** [comment]
I fixed this in TrainerRoad's fork for Xamarin.Mac. IIRC there's an OxyPlot.MonoMac or something that needs the same changes. I can make a PR later. Here's the fix in our fork https://github.com/trainerroad/oxyplot-xamarin/commit/6581f652150d25c0a8f1fa984b861f1dc1415e1c

**Comment by objorke** [comment]
Please make a PR!

**Comment by chaselal** [comment]
I made a pull request. I don't have time to test it right now.
