### ISSUE TITLE
OxyPlot.Xamarin.Mac: don't have a mac nuget package to install from VS 2017 

### ISSUE THREAD

**Issue by hamsternik** [oxyplot/oxyplot-xamarin#85]
OxyPlot already supports Xamarin.Mac platform. oxyplot-xamarin/Sources contains `OxyPlot.Xamarin.Mac` folder, at oxyplot-xamarin/Sources/Examples there also contains a Xamarin.Mac example and so on.

But looking at the `appveyor.yml` I don't see NuGet packing for Xamarin.Mac, as it exists for iOS/Android/Xamarin.Forms in `after_build` phase.

So, as a result, when I try to add a new NuGet package from the VS 2017, typed __oxyplot.__ in the search bar, I don't see Xamarin.Mac package.

**Comment by objorke** [comment]
Try `v2.0.0-preview0001`
