### ISSUE TITLE
X axis points are not aligned with LineSeries points

### ISSUE THREAD

**Issue by ganeshbahirat** [oxyplot/oxyplot-xamarin#86]
I'm using Oxyplot library in my Xamarin forms project to display line graph in Android & iOS apps.

**X axis points are not aligned with LineSeries points.**

![image](https://user-images.githubusercontent.com/459182/49008654-5cd95180-f194-11e8-8897-7bc195107113.png)

          

>  CategoryAxis xAxis = new CategoryAxis 
>                 { 
>                     Position = AxisPosition.Bottom, 
>                     Maximum = Math.Round(xAxisMax + 1), 
>                     Minimum = 0, 
>                     ItemsSource = xAxisPoints,
>                     StartPosition = 1, 
>                     EndPosition = 0 
>                 };

**Comment by jsanalytics** [comment]
It may or may not work, it's up to you to set it up correctly.
![pic025](https://user-images.githubusercontent.com/15644504/49138518-572b5b00-f2bd-11e8-8ead-8f7c8748c335.png)

**Comment by ganeshbahirat** [comment]
I set it as documented but unfortunately its not working.

**Comment by objorke** [comment]
What are the x-coordinates of the points of the `LineSeries`?

**Comment by objorke** [comment]
Closing inactive issues.
