### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Mikilll94** [oxyplot/oxyplot-xamarin#88]
Is anybody maintaining this Github repository?

**Comment by objorke** [comment]
I am following the issue notifications, and will try to approve/give comments on pull requests. Sorry, I don't have much time myself to contribute at the moment.

Please contribute with good quality pull requests to move this forward!

**Comment by objorke** [comment]
So, I would say the answer is no. The project is just sleeping / waiting for contributions :-)
